export const SUPPORTED_TRACK_GENRES = [
  'Ambient',
  'Disco',
  'Drum & Bass',
  'Dubstep',
  'Electronic',
  'Folk & Singer-Songwriter',
  'Hip-hop & Rap',
  'House',
  'Indie',
  'Jazz & Blues',
  'Latin',
  'Metal',
  'Piano',
  'Pop',
  'R&B & Soul',
  'Reggae',
  'Reggaeton',
  'Rock',
  'Soundtrack',
  'Speech',
  'Techno',
  'Trance',
  'Trap',
  'Triphop',
  'World',
] as const;

export type SupportedTrackGenre = (typeof SUPPORTED_TRACK_GENRES)[number];
